### PR TITLE
add new string

### PR DESCRIPTION
**Pull request by BussyBakks**
@rejetto 
add new string in this comment: https://github.com/rejetto/hfs/discussions/402#discussioncomment-8747957
image

### CODE REVIEW

**Comment by rejetto** [comment]
thank you!

**Review by BussyBakks — COMMENTED** [review]
test

**Comment by BussyBakks** [comment]
@rejetto wait my commit is not shown
image

**Comment by BussyBakks** [comment]
image

**Comment by rejetto** [comment]
because it has been moved to the next version (0.52), and you are watching current one

https://github.com/rejetto/hfs/tree/52

**Comment by BussyBakks** [comment]
image
@rejetto still version 1.16 not my 2.1

**Comment by rejetto** [comment]
that commit was not yet pushed, but was on my computer.
now i pushed.

**Pull request merged**
