### PR TITLE
Update Vietnamese to 0.51.0

### PR DESCRIPTION
**Pull request by BussyBakks**
@rejetto 
image

### CODE REVIEW

**Comment by rejetto** [comment]
i see that you are changing "vi" to "vn".
I just checked and found that [MDN states](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) the codes must refer to document [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646), that in turn refer to [ISO 639](https://www.loc.gov/standards/iso639-2/php/code_list.php), that reports for vietnamese "vi", not "vn".
So, this request for change seems to be wrong.
I know that "vn" is used for domains, but that's a different standard.
Do you have any comment on this?

**Comment by rejetto** [comment]
i see that (other than rename) you also made several additions and fixes.
don't worry, these won't be lost.
they will be included in next release.

**Comment by BussyBakks** [comment]
> i see that you are changing "vi" to "vn". I just checked and found that [MDN states](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) the codes must refer to document [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646), that in turn refer to [ISO 639](https://www.loc.gov/standards/iso639-2/php/code_list.php), that reports for vietnamese "vi", not "vn". So, this request for change seems to be wrong. I know that "vn" is used for domains, but that's a different standard. Do you have any comment on this?

uh yeah i forgot "vn" is domain
i will fix soon

**Comment by BussyBakks** [comment]
@rejetto i fixed my work

**Comment by rejetto** [comment]
ok thanks, i will include it in 0.52, tho

**Comment by rejetto** [comment]
you may want to consider strings for 0.52 https://github.com/rejetto/hfs/discussions/402#discussioncomment-8747957

**Comment by BussyBakks** [comment]
> you may want to consider strings for 0.52 [#402 (comment)](https://github.com/rejetto/hfs/discussions/402#discussioncomment-8747957)

@rejetto
[hfs-lang-vi.json](https://github.com/rejetto/hfs/files/14661476/hfs-lang-vi.json)
update more string in this reply:
image

**Pull request merged**
